version: '3.3'

services:
  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - 7001:3000
    volumes:
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=""
      - GF_SECURITY_ADMIN_PASSWORD=""
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - Monitor

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /volumes/prometheus:/etc/prometheus
      - /volumes/prometheus/data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yaml
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    networks:
      - Monitor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:r0
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - Monitor

networks:
  Monitor:
    name: Monitor
